package com.iare.hackathon.information;
import java.util.*;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
@Controller
public class InformationController {
 public record Section(String heading,String body) {}
 public record Page(String title,String intro,List<Section> sections) {}
 private static final Map<String,Page> PAGES=Map.ofEntries(
Map.entry("about",new Page("Company / About","Your workspace, connected.",List.of(new Section("About this platform","Launchpad brings your account, product information, claims and support into one workspace. Browse available products and review their current details before taking action."),new Section("Clear information","Activity figures identify their source. SIMULATED ACTIVITY is a demonstration, not evidence of customers, transactions, profitability or future returns.")))),
Map.entry("contact",new Page("Contact Us","Find the right place to get help.",List.of(new Section("Contact the team","Use Customer Support to send an account or transaction question and follow its status. Sign in to access your support requests."),new Section("Keep your account safe","Include a reference number and a concise description. Never send your password, OTP, full bank credentials or private authentication keys. Only use contact channels published on this page.")))),
Map.entry("faq",new Page("FAQ","A few useful answers.",List.of(new Section("Are the activity numbers real?","DATABASE ACTIVITY reports recorded sign-ins over the last 24 hours and product income claims credited today. It is not an online-user count or net profit. SIMULATED ACTIVITY is generated demo data and does not represent real users or payments."),new Section("How do I get help?","Open Customer Support, describe the issue and include relevant reference numbers. You can review your existing requests there."),new Section("Where can I check my products and withdrawals?","My Product on Home shows your purchases and claim information. The Withdrawal shortcut provides available withdrawal actions and request information."),new Section("Does an earnings display guarantee a return?","No. A displayed amount, projection or demo number is not a guarantee of future income or a successful withdrawal.")))),
Map.entry("terms",new Page("Terms & Conditions","Understand the platform before using it.",List.of(new Section("Using your account","Keep sign-in details private. Use the platform only for lawful activities and do not attempt to access another user's account or manipulate platform records."),new Section("Product and transaction information","Review the current product details and confirmation screen before submitting a payment or request. Simulation and projections are informational and do not establish an entitlement to funds."),new Section("Questions about terms","Company-specific contractual terms have not been supplied for this page. Contact Customer Support for applicable terms before making a financial commitment. This page does not invent fees, return guarantees or dispute deadlines.")))),
Map.entry("privacy",new Page("Privacy Policy","Know what you share.",List.of(new Section("Account and service information","Firebase handles authentication. The application stores account profile information in its connected database. Features you use may also process purchase, claim, payment-reference, withdrawal, bank-detail and support-request information."),new Section("Session and service providers","Session cookies maintain sign-in and protect requests. Enabled integrations include Firebase authentication, Supabase database storage and payment or support-upload providers. External image and social links may contact their respective providers."),new Section("Privacy requests","Use Customer Support to ask about access, correction or deletion of your information. The operator has not yet supplied specific retention periods or a privacy contact address; no deletion deadline or retention promise is made here.")))),
Map.entry("refund-cancellation",new Page("Refund / Cancellation Policy","Get help with a payment or purchase.",List.of(new Section("Request a review","For a duplicate payment, failed transaction or cancellation question, contact Customer Support with the payment or order reference and a description of the issue. Do not share sensitive payment credentials."),new Section("Eligibility and timing","Product-specific refund eligibility, cancellation windows, fees and processing timelines have not been supplied for this page. Ask support for the applicable policy before purchase. Submitting a request does not mean it has been approved."),new Section("Track the outcome","Check your support request and transaction status for updates. Demo activity has no cash value and is not refundable.")))),
Map.entry("withdrawal",new Page("Withdrawal Policy","Review your request and its status.",List.of(new Section("Submitting a request","Use the Withdrawal feature to review available balances, required account details and any limits displayed by the application before submitting. Verify bank details carefully."),new Section("Review and completion","A submitted or pending request is not confirmation that funds have arrived. Follow the status in the application and contact support about an unexpected delay or incorrect information."),new Section("Policy details","No processing-time guarantee, fixed fee schedule or additional eligibility promise is published here because those terms have not been supplied. Request clarification from Customer Support before relying on a withdrawal timetable.")))),
Map.entry("risk-disclaimer",new Page("Risk / Disclaimer","Read the numbers in context.",List.of(new Section("Simulation is not activity","SIMULATED ACTIVITY is generated solely for demonstration. It does not measure real users, transactions, available balances or actual profit."),new Section("Recorded claims are not net profit","DATABASE ACTIVITY totals recorded product income claims for the indicated day and timezone. It does not subtract purchase costs or establish that a withdrawal has been paid. Past recorded activity is not a guarantee of future earnings."),new Section("Make an informed decision","Product projections and displayed earnings are not guaranteed returns or personalized financial advice. Review the terms, costs and risks, and seek independent advice when needed. Do not commit funds based on simulated activity.")))));
 @GetMapping("/information/{slug}") public String page(@PathVariable String slug,Model model){
  Page page=PAGES.get(slug);if(page==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND);
  model.addAttribute("page",page);model.addAttribute("contactPage",slug.equals("contact"));return "information";
 }
}
